<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsRoslynComponent>true</IsRoslynComponent>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <RootNamespace>InfiniteLoathing.Snakeskin.Sample</RootNamespace>
        <CompileExports Condition=" '$(Configuration)' == 'Debug'">true</CompileExports>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Snakeskin\Snakeskin.csproj">
            <OutputItemType>Analyzer</OutputItemType>
            <PrivateAssets>all</PrivateAssets>
            <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
        </ProjectReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    </ItemGroup>
    
    <Import Project="..\Snakeskin\build\Snakeskin.props" />

</Project>
